travis:
  secure:
    BINSTAR_TOKEN: aDsamCufJQZ/Up/PU/LsHC1bmu2OAahL8t8D9QZEr9oqGwjOKkVfIkqMrXox+Ua0ILdOJ1ppQSc0OF2DPpxEQ7lcwX4KgfqITxDnUt4zqabYirQCXhYx+dHxuRjsBlmT2AUNttZbXxE3fdoej2eUc7pTClpIIrOEdAQYuuj+qf0y4ViuHtpoZWj6IAkOhovbRZm07tVjnqyktW/f6V+HdhIZttB8BUG7d6Ob75JeVDCulwirVYqf6zeASGSjYOtagsX7zHtEyMLscAt1U/an/KMpbiC6hde+x80cMyPdS8kohDkTsydI3VEKAq3pHCrDc6D3CAgMnwSC/cY2CkNi1oIqyDKTFHoTSSIKHCWfQrbflx7L1iuUdH7F6nQOTQbLTV6baf8UJ1Ycdenv5Bubj3Lh1U8p/KpKHZnfFIg4tnEba1nnuj9Pc1hLVH+yvuy47oJxEXbiHO6NM/88nVFeJI9ruelfByzQ73ofe5UJ1mReY1JJLK9Zk4z8M9MUhhi6RM/mimciwg5MzBd5hBE+3HxBUNNJKmu8dUP//CZcBNlap9LGfzXb16bZGhcKKJfjxt4tfGO9EwL5uf4Eugh1a60hkW2c1JCzSbZ44fEgZ2xv6JcVRPB/hOBDqZCyCVOWPxzDe9y98NBGOsTcLAWH8NB3tFAYjQwEtxPAaoW7sIg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
